from dotenv import load_dotenv
from openai import OpenAI  # Official OpenAI Python SDK

# Read the .env file and make its variables available
load_dotenv()

# Create an OpenAI client.
client = OpenAI()
# The SDK automatically looks for OPENAI_API_KEY in the environment variables.

# Send a chat completion request to the model.
response = client.chat.completions.create(

    # The AI model that will generate the response.
    model="gpt-4o-mini",

    # Conversation history.
    # Every message must have: (i) role (who sent the message) (ii) content (the actual text)
    messages=[
        {"role": "user", "content": "Hey There"}
    ]
)

# The response object contains a lot of metadata.
# choices[0] -> first generated response
# message    -> assistant's message object
# content    -> actual text generated by the model
print(response.choices[0].message.content)